### ISSUE TITLE
Import errors - logberry\TextOutput.go

### ISSUE THREAD

**Issue by andrewrgoss** [BellerophonMobile/logberry#4]
The following errors occur exist in TextOutput.go within the Logberry package:

    src\github.com\BellerophonMobile\logberry\TextOutput.go:87: cannot use syscall.Stdout (type syscall.Handle) as type int in argument to terminal.IsTerminal
    src\github.com\BellerophonMobile\logberry\TextOutput.go:94: cannot use syscall.Stderr (type syscall.Handle) as type int in argument to terminal.IsTerminal

I'm using a Windows OS. Looks like the [IsTerminal function](https://github.com/BellerophonMobile/logberry/blob/master/terminal/terminal_windows.go) is expecting a fd int data type to be passed in, whereas syscall.Stdout and syscall.Stderr produce regular ints.

**Comment by tom5760** [comment]
Thanks for the bug report!  Let me know if the pushed fix resolves the issue for you.
